server:
  port: 8082

es:
  client:
    servers: localhost:9200

canal:
  client:
    servers: 192.168.30.134:2181
    cluser: true
    destination: placesubscibe

local:
  jdbc:
    url: jdbc:mysql://localhost:3306/db_search?autoReconnect=true&amp;useUnicode=true&amp;characterset=utf8mb4
    username: root
    password: