server:
  port: 8082

es:
  client:
    servers: localhost:9200

local:
  jdbc:
    url: jdbc:mysql://localhost:3306/db_search?autoReconnect=true&amp;useUnicode=true&amp;characterset=utf8mb4
    username: root
    password: root