server:
  port: 8084

es:
  client:
    servers: localhost:9200

canal:
  client:
    servers: 127.0.0.1:11111
    cluser: false
    destination: articlesubscibe

local:
  jdbc:
    url: jdbc:mysql://localhost:3306/db_search?autoReconnect=true&amp;useUnicode=true&amp;characterset=utf8mb4
    username: root
    password: root
